### ISSUE TITLE
git bz attach -e HEAD leads to ImportError: No module named auth

### ISSUE THREAD

**Issue by fitzgen** [mozilla/git-bz-moz#67]
```
fitzgen@nfitzgerald-22150 :: (heap-snapshot-file-actor) :: ~/src/mozilla-central-opt
    $ git config --global bz.username nfitzgerald@mozilla.com

fitzgen@nfitzgerald-22150 :: (heap-snapshot-file-actor) :: ~/src/mozilla-central-opt
    $ git config --global bz.apikey <api-key>

fitzgen@nfitzgerald-22150 :: (heap-snapshot-file-actor) :: ~/src/mozilla-central-opt
    $ git bz attach -e HEAD
Waiting for Emacs...
Traceback (most recent call last):
  File "/Users/fitzgen/bin/moz-git-tools/git-bz", line 1759, in <module>
    do_attach(*args)
  File "/Users/fitzgen/bin/moz-git-tools/git-bz", line 1398, in do_attach
    attach_commits(bug, commits, edit=global_options.edit)
  File "/Users/fitzgen/bin/moz-git-tools/git-bz", line 1327, in attach_commits
    bug.create_patch(description, comment, filename, patch, obsoletes=obsoletes, patch_flags=patch_flags)
  File "/Users/fitzgen/bin/moz-git-tools/git-bz", line 817, in create_patch
    requestee_list = self.server.validate_users(flag_values.requestees, flag_name)
  File "/Users/fitzgen/bin/moz-git-tools/git-bz", line 735, in validate_users
    valid_users = bzexport.validate_users(self.ui, self.api_server, self.auth,
  File "/usr/local/lib/python2.7/site-packages/mercurial/demandimport.py", line 106, in __getattribute__
    self._load()
  File "/usr/local/lib/python2.7/site-packages/mercurial/demandimport.py", line 78, in _load
    mod = _hgextimport(_import, head, globals, locals, None, level)
  File "/usr/local/lib/python2.7/site-packages/mercurial/demandimport.py", line 47, in _hgextimport
    return importfunc(name, globals, *args)
  File "/Users/fitzgen/dot-files/bin/moz-git-tools/git-bz-moz/bzexport.py", line 41, in <module>
    from auth import (
  File "/usr/local/lib/python2.7/site-packages/mercurial/demandimport.py", line 134, in _demandimport
    mod = _hgextimport(_origimport, name, globals, locals)
  File "/usr/local/lib/python2.7/site-packages/mercurial/demandimport.py", line 47, in _hgextimport
    return importfunc(name, globals, *args)
ImportError: No module named auth
```

**Comment by fitzgen** [comment]
If I don't use the -e flag, then it works, but I can't flag for review or obsolete patches.

**Comment by amccreight** [comment]
That's odd. What flags did you attempt to set? (For which people, etc.) Though it looks like some kind of packaging error. What OS are you using?

**Comment by fitzgen** [comment]
I believe I did me+ to carry over an r+ and obsoleted two old patches.

I'm on OSX.

**Comment by nbp** [comment]
I have the same issue.
I fixed it locally, I will submit a patch in a few minutes.

**Comment by amccreight** [comment]
Ah I just wrote a patch, too. ;) Pretty weird. Basically there was an unused import that didn't have the right path. So you can just remove the import. I have no idea why this didn't show up in my testing.
