### ISSUE TITLE
Unicode decoding error in 'git bz apply'

### ISSUE THREAD

**Issue by past** [mozilla/git-bz-moz#88]
gecko$ git bz apply 1291642
Traceback (most recent call last):
  File "/Users/past/src/git-bz-moz/git-bz", line 1788, in <module>
    do_apply(*args)
  File "/Users/past/src/git-bz-moz/git-bz", line 1138, in do_apply
    attachment_data=True)
  File "/Users/past/src/git-bz-moz/git-bz", line 878, in load
    bug._load(bug_reference.id, attachment_data)
  File "/Users/past/src/git-bz-moz/git-bz", line 822, in _load
    self.patches.append(BugAttachment(a))
  File "/Users/past/src/git-bz-moz/git-bz", line 784, in __init__
    diff,
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 10499: ordinal not in range(128)

Manually downloading the diff and applying it using 'git am' works though.

**Comment by aethanyc** [comment]
@chenpighead has the same issue when doing `git bz apply 276079`. The patches in the bug are on mozreview, and contain Unicode characters.

**Comment by amccreight** [comment]
Thanks.

**Comment by chenpighead** [comment]
@aethanyc Nice work!! Thank you 💯 💯 💯
